version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install time
      - export BUCKET=n-codepipeline-bucket
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET 
artifacts:
  type: zip
  files:
    - template.yml
    